"""add_conversation_memory_table

Revision ID: 8ffcf6ca7842
Revises: 537f04d95f39
Create Date: 2026-05-02 20:33:41.891883

"""
from typing import Sequence, Union

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ffcf6ca7842'
down_revision: Union[str, Sequence[str], None] = '537f04d95f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_conversation_id'), 'conversation_memory', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_source_type'), 'conversation_memory', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memory_source_type'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_conversation_id'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###
