"""add_ondelete_cascade_to_foreign_keys

Revision ID: ae30986eadf1
Revises: 8ffcf6ca7842
Create Date: 2026-05-02 21:15:14.576478

"""
from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae30986eadf1'
down_revision: Union[str, Sequence[str], None] = '8ffcf6ca7842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_user_id_fkey'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_memory_conversation_id_fkey'), 'conversation_memory', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_memory', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_conversation_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_citations_message_id_fkey'), 'message_citations', type_='foreignkey')
    op.drop_constraint(op.f('message_citations_document_id_fkey'), 'message_citations', type_='foreignkey')
    op.create_foreign_key(None, 'message_citations', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_citations', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_citations', type_='foreignkey')
    op.drop_constraint(None, 'message_citations', type_='foreignkey')
    op.create_foreign_key(op.f('message_citations_document_id_fkey'), 'message_citations', 'document', ['document_id'], ['id'])
    op.create_foreign_key(op.f('message_citations_message_id_fkey'), 'message_citations', 'message', ['message_id'], ['id'])
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_conversation_id_fkey'), 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversation_memory', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_memory_conversation_id_fkey'), 'conversation_memory', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_user_id_fkey'), 'conversation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
